# .github/workflows/main.yml

name: Run Java Selenium Tests and Notify

# This controls when the action will run. 
on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/*"
  pull_request:
    branches: [ "main" ]
  #This adds the schedule trigger to run the workflow every day at midnight
  schedule:
    - cron: '0 0 * * *'


jobs:
  # A job named "build-and-test"
  build-and-test:
    
    # 1. SETTING THE VM with Matrix STRATEGY:
    # This job will run on the multiple OS specified in the matrix
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    # THIS BLOCK IS THE FIX:
    # It forces the job to use GitHub's cloud runners,
    # bypassing your local machine and its proxy.
    runs-on:
      group: github-hosted
      labels: ${{ matrix.os }}
    

    steps:
      # Step 1: Checks out your repository code onto the VM
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: SETTING UP JAVA:
      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Step 3: RUNNING THE TESTS:
      - name: Run tests with Maven
        run: mvn test
        env:
          WEB_USER: ${{ secrets.WEB_USER }}
          WEB_PASS: ${{ secrets.WEB_PASS }}
          WEB_URL: ${{ secrets.WEB_URL }}

      # Step 4: ARCHIVING TEST REPORTS:
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # This name is now unique for each OS
          name: test-reports-${{ matrix.os }}
          path: target/allure-reports/*.xml

      # Step 5: SEND SLACK NOTIFICATION (THE RELIABLE WAY)
      - name: Send Slack Notification
        if: always() # This ensures the step runs even if 'Run tests' fails
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # This is your JSON payload, written in YAML format
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && '#36a64f' || '#d00000' }}",
                  "title": "Selenium Test Run: ${{ job.status }} on ${{ matrix.os }}",
                  "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Triggered by",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "Workflow",
      
                      "value": "${{ github.workflow }}",
                      "short": true
                    },
                    {
                      "title": "Event",
                      "value": "${{ github.event_name }}",
                      "short": true
                    }
                  ],
                  "fallback": "Test run on ${{ matrix.os }} ${{ job.status }}: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
        env:
          # The action will automatically find and use this secret
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

