# .github/workflows/main.yml

name: Run Java Selenium Tests and Notify

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/*"
  pull_request:
    branches: [ "main" ]
  #This adds the schedule trigger to run the workflow every day at midnight
  schedule:
    - cron: '0 0 * * *'

jobs:
  # JOB 1: RUN ALL THE TESTS
  build-and-test:
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests with Maven
        run: mvn test
        env:
          WEB_USER: ${{ secrets.WEB_USER }}
          WEB_PASS: ${{ secrets.WEB_PASS }}
          WEB_URL: ${{ secrets.WEB_URL }}

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.os }}
          path: target/allure-reports/*.xml

  # JOB 2: SEND THE NOTIFICATION (RUNS ONCE, ON UBUNTU)
  send-notification:
    # This job needs the first one to finish
    needs: build-and-test 
    
    # This ensures it runs even if tests fail
    if: always() 
    
    # We run this on Ubuntu because it's stable
    runs-on: ubuntu-latest 
    
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # THIS PAYLOAD IS NOW REFORMATTED USING SLACK "BLOCKS"
          payload: |
            {
              "text": "Selenium Test Run: ${{ needs.build-and-test.result }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Selenium Test Run: ${{ needs.build-and-test.result == 'success' && '✅ Success' || '❌ Failure' }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A test run was triggered by *${{ github.actor }}* on the `${{ github.ref_name }}` branch."
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Run Details"
                    },
                    "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                    "style": "${{ needs.build-and-test.result == 'success' && 'primary' || 'danger' }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow:*\n${{ github.workflow }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event:*\n${{ github.event_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n${{ needs.build-and-test.result }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

